"""Strict greedy decoding for opt-in versioned language checkpoints."""
import torch

from .corpus import require
from .neural import CausalLM
from .tracking import digest


@torch.no_grad()
def generate(model, tokenizer, prompt, max_new_tokens):
    require(isinstance(prompt, str), "generation prompt must be text")
    require(type(max_new_tokens) is int and 1 <= max_new_tokens <= 512, "generation budget must be 1..512 tokens")
    require(model.cfg.vocab_size == tokenizer.vocab_size, "generation vocabulary mismatch")
    require(len(prompt.encode("utf-8")) <= 262144, "generation prompt exceeds byte budget")
    prefix = [tokenizer.bos_id]+tokenizer.encode(prompt)
    require(len(prefix)+max_new_tokens <= model.cfg.context, "generation budget exceeds context; no implicit truncation")
    tokens, generated = list(prefix), []
    termination, error, output = "token_budget", None, None
    was_training = model.training
    model.eval()
    try:
        for _ in range(max_new_tokens):
            logits = model(torch.tensor([tokens]))[0,-1]
            require(bool(torch.isfinite(logits).all()), "nonfinite generation logits")
            token = int(logits.argmax())
            generated.append(token)
            if token == tokenizer.eos_id:
                termination = "eos"
                break
            if token in {tokenizer.bos_id, tokenizer.pad_id}:
                termination, error = "invalid_special_token", "BOS/PAD emitted inside response"
                break
            tokens.append(token)
        if error is None:
            try:
                output = tokenizer.decode([t for t in generated if t != tokenizer.eos_id], strict=True)
            except UnicodeError:
                termination, error = "invalid_utf8", "generated bytes are not complete UTF-8"
    finally:
        model.train(was_training)
    return {"schema": "aim-greedy-generation-v1", "tokenizer_hash": digest(tokenizer.specification()),
            "prompt_hash": digest(prompt.encode("utf-8")), "prompt_tokens": len(prefix), "generated_ids": generated,
            "generated_tokens": len(generated), "max_new_tokens": max_new_tokens, "termination": termination,
            "text": output, "error": error, "scope": "greedy decoding trace; no correctness or verification claim"}


class TokenizedCausalLM(CausalLM):
    def generate_text(self, tokenizer, prompt, max_new_tokens):
        self.last_generation = None
        self.last_generation = generate(self, tokenizer, prompt, max_new_tokens)
        require(self.last_generation["error"] is None, self.last_generation["error"] or "generation failed")
        return self.last_generation["text"]
