"""Interchangeable researcher adapters; the reference algorithm is explicitly non-neural."""
from __future__ import annotations

import json

from .contracts import ContractError, Hypothesis, ResearchState


def predict(coefficients, x):
    result = 0.0
    for c in reversed(coefficients):
        result = result * x + c
    return result


def interpolate(points):
    """Small floating-point Lagrange interpolator for a deterministic baseline."""
    result = [0.0] * len(points)
    for i, (x, y) in enumerate(points):
        polynomial = [1.0]
        denominator = 1.0
        for j, (other, _) in enumerate(points):
            if i == j:
                continue
            denominator *= x - other
            if denominator == 0:
                raise ContractError("Duplicate observation coordinates")
            expanded = [0.0] * (len(polynomial) + 1)
            for k, c in enumerate(polynomial):
                expanded[k] -= other * c
                expanded[k + 1] += c
            polynomial = expanded
        for k, c in enumerate(polynomial):
            result[k] += c * y / denominator
    return tuple(result)


class PolynomialResearcher:
    model_id = "algorithmic-polynomial-reference-v1"

    def plan(self, state: ResearchState):
        return ["Retrieve versioned observations for the topic", "Compare linear and quadratic hypotheses",
                "Predict a new measurement", "Request independent measurement and verify each prediction",
                "Revise claims and report check scope with exact evidence"]

    def hypothesize(self, state: ResearchState):
        observations = sorted(state.observations)
        evidence_ids = tuple(e.id for e in state.evidence)
        return [Hypothesis(f"h-degree-{degree}", interpolate(observations[:degree + 1]), evidence_ids,
                           f"Degree {degree} interpolant; fit is a candidate, not a law proof")
                for degree in (1, 2) if len(observations) >= degree + 1]


class TransformerResearcher:
    """Uses only a local AIM checkpoint. Invalid generations fail closed; no fixture fallback."""
    def __init__(self, checkpoint, max_new_tokens=160):
        from .neural import load_lm
        from .tracking import file_hash
        self.model, self.tokenizer, _ = load_lm(checkpoint)
        self.model.eval()
        self.model_id = "aim-random-origin-checkpoint-" + file_hash(checkpoint)
        self.max_new_tokens = max_new_tokens

    def plan(self, state):
        return ["Generate candidate hypotheses from retrieved observations", "Verify generated candidates",
                "Publish only scoped checked results"]

    def hypothesize(self, state):
        prompt = json.dumps({"task": "Return JSON {coefficients:[[c0,c1],[c0,c1,c2]]}",
                             "observations": state.observations, "target_x": state.target_x})
        text = self.model.generate_text(self.tokenizer, prompt, self.max_new_tokens)
        try:
            output = json.loads(text)
            if set(output) != {"coefficients"} or not 1 <= len(output["coefficients"]) <= 3:
                raise ValueError("Invalid output schema")
            return [Hypothesis(f"h-neural-{i}", tuple(coef), tuple(e.id for e in state.evidence),
                               "Generated by AIM checkpoint; requires independent verification")
                    for i, coef in enumerate(output["coefficients"])]
        except (ValueError, TypeError, KeyError) as exc:
            raise ContractError(f"Researcher emitted invalid hypothesis JSON: {text[:160]!r}") from exc
